# Custom AI Function using your own API keys
# This is a template for creating a custom function that uses your OpenAI/Claude keys
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-custom-ai
  annotations:
    ai.msdp.com/description: "Custom AI function using personal OpenAI and Claude API keys"
    ai.msdp.com/provider: "custom"
spec:
  package: "xpkg.upbound.io/msdp-platform/function-custom-ai:v1.0.0"  # We'll build this
  
---
# Secret for storing your API keys
apiVersion: v1
kind: Secret
metadata:
  name: ai-api-keys
  namespace: crossplane-system
type: Opaque
stringData:
  openai-api-key: "your-openai-key-here"  # Replace with your actual key
  claude-api-key: "your-claude-key-here"  # Replace with your actual key
  
---
# DeploymentRuntimeConfig to inject the API keys
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: custom-ai-runtime-config
spec:
  deploymentTemplate:
    spec:
      template:
        spec:
          containers:
          - name: package-runtime
            env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-api-keys
                  key: openai-api-key
            - name: CLAUDE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-api-keys
                  key: claude-api-key
