# XRD and Compositions - Infrastructure Layer (Cluster-scoped)
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: x3tierapps.platform.msdp.com
spec:
  group: platform.msdp.com
  names:
    kind: X3TierApp
    plural: x3tierapps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  environment:
                    type: string
                    description: Environment (dev, staging, prod)
                  serviceName:
                    type: string
                    description: Service name
                  region:
                    type: string
                    description: AWS region
                    default: eu-west-1
                required:
                - environment
                - serviceName
            required:
            - parameters
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
  claimNames:
    kind: TierApp
    plural: tierapps

