services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: msdp-payment-service-dev
    ports:
      - "3007:3007" # Using centralized port allocation
    environment:
      - NODE_ENV=development
      - PORT=3007
      # Database configuration (Payment Service owns payment data)
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=msdp_payments
      - DB_USER=msdp_user
      - DB_PASSWORD=msdp_password
      - DATABASE_URL=postgresql://msdp_user:msdp_password@postgres:5432/msdp_payments
      # Service URLs (for cross-service communication)
      - USER_SERVICE_URL=http://host.docker.internal:3003
      - ORDER_SERVICE_URL=http://host.docker.internal:3006
      - MERCHANT_SERVICE_URL=http://host.docker.internal:3002
      # Payment Provider Configuration
      - STRIPE_SECRET_KEY=sk_test_demo_key
      - STRIPE_PUBLISHABLE_KEY=pk_test_demo_key
      - PAYPAL_CLIENT_ID=demo_paypal_client_id
      - PAYPAL_CLIENT_SECRET=demo_paypal_secret
      # Authentication
      - JWT_SECRET=dev-payment-jwt-secret
      - JWT_EXPIRES_IN=7d
      # CORS
      - CORS_ORIGIN=http://localhost:4001,http://localhost:5001,http://localhost:5002,http://localhost:5003,http://localhost:5004,http://localhost:3006
      - LOG_LEVEL=debug
    volumes:
      # Source code hot reload (optimized)
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:ro
      # Logs directory
      - ./logs:/app/logs:delegated
      # Exclude node_modules from host (use named volume)
      - payment_service_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - msdp-payment-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: msdp-payment-postgres-dev
    environment:
      - POSTGRES_DB=msdp_payments
      - POSTGRES_USER=msdp_user
      - POSTGRES_PASSWORD=msdp_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5439:5432" # Using centralized port allocation
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-payment-schema.sql:ro
      - ./database/permissions.sql:/docker-entrypoint-initdb.d/02-payment-permissions.sql:ro
    networks:
      - msdp-payment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msdp_user -d msdp_payments"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: msdp-payment-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@msdp.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "8089:80" # Using centralized port allocation
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - msdp-payment-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: msdp_payment_postgres_data
  pgadmin_data:
    name: msdp_payment_pgadmin_data
  payment_service_node_modules:
    name: msdp_payment_service_node_modules

networks:
  msdp-payment-network:
    driver: bridge
    name: msdp-payment-network
