apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: msdp-platform
data:
  app-config.yaml: |
    app:
      title: MSDP Service Catalog
      baseUrl: http://backstage.msdp.local
      listen:
        host: 0.0.0.0
        port: 3000

    backend:
      baseUrl: http://backstage-api.msdp.local
      listen:
        host: 0.0.0.0
        port: 7007
      
      cors:
        origin: 
          - http://backstage.msdp.local
          - http://localhost:*
        credentials: true

      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      environment: development
      providers:
        guest: {}

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, User, Group, Template]
      
      locations:
        - type: file
          target: /app/catalog/msdp-services.yaml
        - type: file
          target: /app/catalog/msdp-teams.yaml

    integrations:
      github:
        - host: github.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: msdp-platform
  labels:
    app: backstage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: spotify/backstage:latest
          ports:
            - containerPort: 3000
              name: frontend
            - containerPort: 7007
              name: backend
          env:
            - name: NODE_ENV
              value: "development"
          volumeMounts:
            - name: backstage-config
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
            - name: catalog-volume
              mountPath: /app/catalog
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: backstage-config
          configMap:
            name: backstage-config
        - name: catalog-volume
          configMap:
            name: msdp-catalog
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: msdp-platform
spec:
  selector:
    app: backstage
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 7007
      targetPort: 7007
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage-ingress
  namespace: msdp-platform
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: backstage.msdp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage-service
                port:
                  number: 3000
    - host: backstage-api.msdp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage-service
                port:
                  number: 7007
