apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msdp-3tier-platform-core
  namespace: argocd
  labels:
    app.kubernetes.io/name: msdp-3tier-platform-core
    app.kubernetes.io/part-of: msdp-platform
spec:
  project: default
  source:
    repoURL: https://github.com/msdp-platform/msdp-platform-core.git
    targetRevision: HEAD
    path: infrastructure/3tier-architecture
  destination:
    server: https://kubernetes.default.svc
    namespace: user-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
