# Tier 2: Production Lambda Function - Core Infrastructure
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: user-service-lambda-production
  namespace: user-service
  labels:
    tier: api-logic
    service: user-service
    environment: production
spec:
  forProvider:
    region: eu-west-1
    handler: index.handler
    runtime: nodejs18.x
    role: arn:aws:iam::319422413814:role/user-service-lambda-role
    # Using properly created zip file
    s3Bucket: lambda-code-bucket-msdp-2025-09-24-21-33
    s3Key: user-service-lambda-production.zip
    description: "User Service API Lambda Function - Production Core Infrastructure"
    timeout: 30
    memorySize: 512
    environment:
      - variables:
          NODE_ENV: production
          SERVICE_NAME: user-service
          TIER: api-logic
          ARCHITECTURE: 3-tier-production
    tags:
      Environment: production
      Service: user-service
      Tier: api-logic
      Purpose: core-infrastructure
      Project: msdp-platform
