apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msdp-3tier-foundation
  namespace: argocd
  labels:
    app.kubernetes.io/name: msdp-3tier-foundation
    app.kubernetes.io/component: argocd-application
    app.kubernetes.io/part-of: msdp-platform
    test.msdp.com/type: fresh-no-touch
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    platform.msdp.com/description: "Foundation app - applies XRD and Composition first"
spec:
  project: default
  source:
    repoURL: https://github.com/msdp-platform/msdp-platform-core.git
    targetRevision: dev
    path: infrastructure/crossplane-infra/fresh/foundation
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
